spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ameda
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 5555

jwt:
  auth:
    converter:
      resource-id: ameda-rest-api
      principal-attribute: preferred_username